"""Index the run directories so a review stops opening every one of them.

    python3 -m tools.learn.runs            rewrite learn/runs/index.md
    python3 -m tools.learn.runs --check    fail if it is stale

One line per run, newest first, carrying what a reader would otherwise have to
open `run.json` and both CSVs to learn: the mode, the day, how many channels
the run read, how many decisions it recorded, and how many of those rows carry
a grade. The last column is the one that earns the file. `review-evals` asks
where the grading is every time it runs, and the answer used to cost a read of
every CSV under here.

A row counts as adjudicated when its `adjudication` cell is filled, which is
the test `tools/learn/evals.py` already applies in `graded_rows`, and this
calls that function rather than restating it. Counting the other grading
columns instead would print a number here that disagrees with
`python3 -m tools.source.sweep grades`, and an index that disagrees with the
report it summarizes is worse than no index.

The generator owns the table and leaves the prose above it alone, the same
split `tools/apply/companies.py` uses. Nothing in the table is summarized, so
nothing in it can drift: re-run this and commit what it produced.
"""

import csv
import json
import sys
from collections import Counter

from tools.core.repo import ROOT
from tools.learn import evals

INSIDE = "learn/runs"
INDEX = ROOT / INSIDE / "index.md"
START, END = "<!-- index:start -->", "<!-- index:end -->"
STEPS = ("sweep.csv", "judgment.csv")
# `-` rather than 0, because a channel that returned nothing is recorded as 0
# and a run that never had channels is a different thing from one that read none
MISSING = "-"
HEADER = (
    "# Runs\n\n"
    "Every sweep and every judgment pass writes a directory under here, named "
    "for the second it started, holding `run.json` and the CSV of what it "
    "decided. This is the list of them, newest first, so a review can see "
    "where the grading is without opening each one.\n\n"
    "Generated by `python3 -m tools.learn.runs`, so it is rewritten rather "
    "than edited. Every number is read off the files it names, which means "
    "the rows column counts what is still on disk: a run that lost a CSV "
    "reads small here, and its `run.json` says so.\n\n")


def runs(root=ROOT):
    """Every run directory, newest first.

    A directory is named for the second it started, so sorting by name sorts
    by time. `run.json` is what makes a directory a run: it is written last
    and the index of a half-written run would be read as a run that failed.
    """
    return sorted((d for d in (root / INSIDE).glob("*")
                   if (d / "run.json").exists()), reverse=True)


def decisions(run):
    """How many decisions this run recorded, sweep and judgment alike."""
    total = 0
    for name in STEPS:
        if not (run / name).exists():
            continue
        with open(run / name, newline="") as f:
            total += sum(1 for _ in csv.DictReader(f))
    return total


def entry(run, recorded, graded):
    meta = json.loads((run / "run.json").read_text())
    channels = meta.get("channels")
    return (f"| [{run.name}]({run.name}/run.json) "
            f"| {meta.get('mode', MISSING)} "
            f"| {meta.get('started', run.name)[:10]} "
            f"| {MISSING if channels is None else len(channels)} "
            f"| {recorded} | {graded} |")


def build(root=ROOT):
    graded = Counter(name for name, _, _ in evals.graded_rows(root / INSIDE))
    counted = [(run, decisions(run)) for run in runs(root)]
    total = sum(n for _, n in counted)
    return "\n".join([
        f"{len(counted)} runs, {total} recorded decisions, "
        f"{sum(graded.values())} of them adjudicated.", "",
        "| run | mode | date | channels | rows | adjudicated |",
        "|---|---|---|---|---|---|",
        *(entry(run, n, graded[run.name]) for run, n in counted)]) + "\n"


def render(root=ROOT):
    index = root / INSIDE / "index.md"
    old = index.read_text() if index.exists() else f"{HEADER}{START}\n{END}\n"
    head, _, rest = old.partition(START)
    _, _, tail = rest.partition(END)
    return f"{head}{START}\n\n{build(root)}\n{END}{tail}"


def wanted_here(root=ROOT):
    """Whether this instance has anything to index yet.

    A fresh clone of the template ships the directory holding nothing but its
    `.gitkeep`, and a check that demands an index of nothing turns a first
    clone into a blocked first commit. That has been the bug three times. Once
    the index exists it stays checked, so emptying the directory reports
    rather than going quiet.
    """
    return bool(runs(root)) or (root / INSIDE / "index.md").exists()


def main(argv):
    if not wanted_here():
        print(f"skipped: nothing under {INSIDE}/ in this instance yet")
        return
    text = render()
    if "--check" in argv:
        current = INDEX.read_text() if INDEX.exists() else ""
        if current != text:
            sys.exit(f"{INSIDE}/index.md is stale; "
                     "run python3 -m tools.learn.runs")
        return
    INDEX.write_text(text)
    print(f"wrote {INDEX.relative_to(ROOT)}: {len(runs())} runs")


if __name__ == "__main__":
    main(sys.argv[1:])
